function getEscolas() {
    var a = [
     {
    "Ano":2012,
    "Regiao":"Norte",
    "UF":"AM",
    "CodigoMun":1301852,
    "Municipio":"IRANDUBA",
    "CodigoEscola":13076540,
    "Nome":"ESC URSULINA MACEDO",
    "Localizacao":"Rural",
    "Rede":"Municipal",
    "ID_LATITUDE":-60.17770473,
    "ID_LONGITUDE":-3.201231442,
    "Eudcacao_Infantil_Total":"--",
    "Eudcacao_Infantil_Creche":"--",
    "Eudcacao_Infantil_Pre-Escola":"--",
    "Ensino_Fundamental_Total":8,
    "Ensino_Fundamental_Anos Iniciais":"--",
    "Ensino_Fundamental_Anos Finais":"--",
    "Ensino_Fundamental_1":"--",
    "Ensino_Fundamental_2":"--",
    "Ensino_Fundamental_3":"--",
    "Ensino_Fundamental_4":"--",
    "Ensino_Fundamental_5":"--",
    "Ensino_Fundamental_6":"--",
    "Ensino_Fundamental_7":"--",
    "Ensino_Fundamental_8":"--",
    "Ensino_Fundamental_9":"--",
    "Turmas_Unificadas_1":8,
    "Ensino_Medio_Total Medio":"--",
    "Ensino_Medio_1":"--",
    "Ensino_Medio_2":"--",
    "Ensino_Medio_3":"--",
    "Ensino_Medio_4":"--",
    "FIELD33":"--"
  },
  {
    "Ano":2012,
    "Regiao":"Norte",
    "UF":"AM",
    "CodigoMun":1301852,
    "Municipio":"IRANDUBA",
    "CodigoEscola":13079697,
    "Nome":"ESC SANTA HELENA",
    "Localizacao":"Rural",
    "Rede":"Municipal",
    "ID_LATITUDE":-60.194411,
    "ID_LONGITUDE":-3.273661,
    "Eudcacao_Infantil_Total":"--",
    "Eudcacao_Infantil_Creche":"--",
    "Eudcacao_Infantil_Pre-Escola":"--",
    "Ensino_Fundamental_Total":20,
    "Ensino_Fundamental_Anos Iniciais":"--",
    "Ensino_Fundamental_Anos Finais":"--",
    "Ensino_Fundamental_1":"--",
    "Ensino_Fundamental_2":"--",
    "Ensino_Fundamental_3":"--",
    "Ensino_Fundamental_4":"--",
    "Ensino_Fundamental_5":"--",
    "Ensino_Fundamental_6":"--",
    "Ensino_Fundamental_7":"--",
    "Ensino_Fundamental_8":"--",
    "Ensino_Fundamental_9":"--",
    "Turmas_Unificadas_1":20,
    "Ensino_Medio_Total Medio":"--",
    "Ensino_Medio_1":"--",
    "Ensino_Medio_2":"--",
    "Ensino_Medio_3":"--",
    "Ensino_Medio_4":"--",
    "FIELD33":"--"
  },
  {
    "Ano":2012,
    "Regiao":"Norte",
    "UF":"AM",
    "CodigoMun":1301852,
    "Municipio":"IRANDUBA",
    "CodigoEscola":13079700,
    "Nome":"ESCOLA MUNICIPAL NOEMI SANTOS PEREIRA",
    "Localizacao":"Urbana",
    "Rede":"Municipal",
    "ID_LATITUDE":-60.16497266,
    "ID_LONGITUDE":-3.216018304,
    "Eudcacao_Infantil_Total":20.1,
    "Eudcacao_Infantil_Creche":14,
    "Eudcacao_Infantil_Pre-Escola":22.2,
    "Ensino_Fundamental_Total":21.4,
    "Ensino_Fundamental_Anos Iniciais":21.4,
    "Ensino_Fundamental_Anos Finais":"--",
    "Ensino_Fundamental_1":21.6,
    "Ensino_Fundamental_2":26,
    "Ensino_Fundamental_3":22.5,
    "Ensino_Fundamental_4":19.4,
    "Ensino_Fundamental_5":17.3,
    "Ensino_Fundamental_6":"--",
    "Ensino_Fundamental_7":"--",
    "Ensino_Fundamental_8":"--",
    "Ensino_Fundamental_9":"--",
    "Turmas_Unificadas_1":"--",
    "Ensino_Medio_Total Medio":"--",
    "Ensino_Medio_1":"--",
    "Ensino_Medio_2":"--",
    "Ensino_Medio_3":"--",
    "Ensino_Medio_4":"--",
    "FIELD33":"--"
  },
  {
    "Ano":2012,
    "Regiao":"Norte",
    "UF":"AM",
    "CodigoMun":1301852,
    "Municipio":"IRANDUBA",
    "CodigoEscola":13081268,
    "Nome":"ESCOLA ESTADUAL CECILIA CARNEIRO DE OLIVEIRA",
    "Localizacao":"Urbana",
    "Rede":"Estadual",
    "ID_LATITUDE":-60.188923,
    "ID_LONGITUDE":-3.280501,
    "Eudcacao_Infantil_Total":"--",
    "Eudcacao_Infantil_Creche":"--",
    "Eudcacao_Infantil_Pre-Escola":"--",
    "Ensino_Fundamental_Total":29.1,
    "Ensino_Fundamental_Anos Iniciais":27.6,
    "Ensino_Fundamental_Anos Finais":31.2,
    "Ensino_Fundamental_1":23,
    "Ensino_Fundamental_2":28.7,
    "Ensino_Fundamental_3":27.3,
    "Ensino_Fundamental_4":26.5,
    "Ensino_Fundamental_5":34.5,
    "Ensino_Fundamental_6":32.5,
    "Ensino_Fundamental_7":27,
    "Ensino_Fundamental_8":37,
    "Ensino_Fundamental_9":30.5,
    "Turmas_Unificadas_1":"--",
    "Ensino_Medio_Total Medio":"--",
    "Ensino_Medio_1":"--",
    "Ensino_Medio_2":"--",
    "Ensino_Medio_3":"--",
    "Ensino_Medio_4":"--",
    "FIELD33":"--"
  },
  {
    "Ano":2012,
    "Regiao":"Norte",
    "UF":"AM",
    "CodigoMun":1301852,
    "Municipio":"IRANDUBA",
    "CodigoEscola":13082469,
    "Nome":"ESC ANA BARBOSA DE CASTRO",
    "Localizacao":"Urbana",
    "Rede":"Municipal",
    "ID_LATITUDE":-60.0835088,
    "ID_LONGITUDE":-3.1659989,
    "Eudcacao_Infantil_Total":"--",
    "Eudcacao_Infantil_Creche":"--",
    "Eudcacao_Infantil_Pre-Escola":"--",
    "Ensino_Fundamental_Total":31,
    "Ensino_Fundamental_Anos Iniciais":27.3,
    "Ensino_Fundamental_Anos Finais":34.7,
    "Ensino_Fundamental_1":19,
    "Ensino_Fundamental_2":28,
    "Ensino_Fundamental_3":26,
    "Ensino_Fundamental_4":32,
    "Ensino_Fundamental_5":30,
    "Ensino_Fundamental_6":41,
    "Ensino_Fundamental_7":37,
    "Ensino_Fundamental_8":26.5,
    "Ensino_Fundamental_9":34,
    "Turmas_Unificadas_1":"--",
    "Ensino_Medio_Total Medio":"--",
    "Ensino_Medio_1":"--",
    "Ensino_Medio_2":"--",
    "Ensino_Medio_3":"--",
    "Ensino_Medio_4":"--",
    "FIELD33":"--"
  },
  {
    "Ano":2012,
    "Regiao":"Norte",
    "UF":"AM",
    "CodigoMun":1301852,
    "Municipio":"IRANDUBA",
    "CodigoEscola":13089536,
    "Nome":"ESC MARIA IOLANDA MAURICIO VIANA",
    "Localizacao":"Rural",
    "Rede":"Municipal",
    "ID_LATITUDE":-60.18627316,
    "ID_LONGITUDE":-3.273629155,
    "Eudcacao_Infantil_Total":16,
    "Eudcacao_Infantil_Creche":"--",
    "Eudcacao_Infantil_Pre-Escola":16,
    "Ensino_Fundamental_Total":20.5,
    "Ensino_Fundamental_Anos Iniciais":"--",
    "Ensino_Fundamental_Anos Finais":"--",
    "Ensino_Fundamental_1":"--",
    "Ensino_Fundamental_2":"--",
    "Ensino_Fundamental_3":"--",
    "Ensino_Fundamental_4":"--",
    "Ensino_Fundamental_5":"--",
    "Ensino_Fundamental_6":"--",
    "Ensino_Fundamental_7":"--",
    "Ensino_Fundamental_8":"--",
    "Ensino_Fundamental_9":"--",
    "Turmas_Unificadas_1":20.5,
    "Ensino_Medio_Total Medio":"--",
    "Ensino_Medio_1":"--",
    "Ensino_Medio_2":"--",
    "Ensino_Medio_3":"--",
    "Ensino_Medio_4":"--",
    "FIELD33":"--"
  },
  {
    "Ano":2012,
    "Regiao":"Norte",
    "UF":"AM",
    "CodigoMun":1301852,
    "Municipio":"IRANDUBA",
    "CodigoEscola":13094475,
    "Nome":"CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    "Localizacao":"Urbana",
    "Rede":"Estadual",
    "ID_LATITUDE":-60.156341,
    "ID_LONGITUDE":-3.166934,
    "Eudcacao_Infantil_Total":"--",
    "Eudcacao_Infantil_Creche":"--",
    "Eudcacao_Infantil_Pre-Escola":"--",
    "Ensino_Fundamental_Total":"--",
    "Ensino_Fundamental_Anos Iniciais":"--",
    "Ensino_Fundamental_Anos Finais":"--",
    "Ensino_Fundamental_1":"--",
    "Ensino_Fundamental_2":"--",
    "Ensino_Fundamental_3":"--",
    "Ensino_Fundamental_4":"--",
    "Ensino_Fundamental_5":"--",
    "Ensino_Fundamental_6":"--",
    "Ensino_Fundamental_7":"--",
    "Ensino_Fundamental_8":"--",
    "Ensino_Fundamental_9":"--",
    "Turmas_Unificadas_1":"--",
    "Ensino_Medio_Total Medio":"--",
    "Ensino_Medio_1":"--",
    "Ensino_Medio_2":"--",
    "Ensino_Medio_3":"--",
    "Ensino_Medio_4":"--",
    "FIELD33":"--"
  },
  {
    "Ano":2012,
    "Regiao":"Norte",
    "UF":"AM",
    "CodigoMun":1301852,
    "Municipio":"IRANDUBA",
    "CodigoEscola":13095773,
    "Nome":"ESC MUN PREFEITO NONATO LOPES",
    "Localizacao":"Urbana",
    "Rede":"Municipal",
    "ID_LATITUDE":-60.086324,
    "ID_LONGITUDE":-3.166917,
    "Eudcacao_Infantil_Total":"--",
    "Eudcacao_Infantil_Creche":"--",
    "Eudcacao_Infantil_Pre-Escola":"--",
    "Ensino_Fundamental_Total":27.5,
    "Ensino_Fundamental_Anos Iniciais":27.5,
    "Ensino_Fundamental_Anos Finais":"--",
    "Ensino_Fundamental_1":28,
    "Ensino_Fundamental_2":29,
    "Ensino_Fundamental_3":26.2,
    "Ensino_Fundamental_4":"--",
    "Ensino_Fundamental_5":"--",
    "Ensino_Fundamental_6":"--",
    "Ensino_Fundamental_7":"--",
    "Ensino_Fundamental_8":"--",
    "Ensino_Fundamental_9":"--",
    "Turmas_Unificadas_1":"--",
    "Ensino_Medio_Total Medio":"--",
    "Ensino_Medio_1":"--",
    "Ensino_Medio_2":"--",
    "Ensino_Medio_3":"--",
    "Ensino_Medio_4":"--",
    "FIELD33":"--"
  },
  {
    "Ano":2012,
    "Regiao":"Norte",
    "UF":"AM",
    "CodigoMun":1301852,
    "Municipio":"IRANDUBA",
    "CodigoEscola":13096435,
    "Nome":"ESCOLA ESTADUAL THOMAS EUGENE LOVEJOY",
    "Localizacao":"Rural",
    "Rede":"Estadual",
    "ID_LATITUDE":-60.1750524,
    "ID_LONGITUDE":-3.201032191,
    "Eudcacao_Infantil_Total":"--",
    "Eudcacao_Infantil_Creche":"--",
    "Eudcacao_Infantil_Pre-Escola":"--",
    "Ensino_Fundamental_Total":7.8,
    "Ensino_Fundamental_Anos Iniciais":"--",
    "Ensino_Fundamental_Anos Finais":7.8,
    "Ensino_Fundamental_1":"--",
    "Ensino_Fundamental_2":"--",
    "Ensino_Fundamental_3":"--",
    "Ensino_Fundamental_4":"--",
    "Ensino_Fundamental_5":"--",
    "Ensino_Fundamental_6":8,
    "Ensino_Fundamental_7":4,
    "Ensino_Fundamental_8":8,
    "Ensino_Fundamental_9":11,
    "Turmas_Unificadas_1":"--",
    "Ensino_Medio_Total Medio":11.7,
    "Ensino_Medio_1":7,
    "Ensino_Medio_2":20,
    "Ensino_Medio_3":8,
    "Ensino_Medio_4":"--",
    "FIELD33":"--"
  },
  {
    "Ano":2012,
    "Regiao":"Norte",
    "UF":"AM",
    "CodigoMun":1301852,
    "Municipio":"IRANDUBA",
    "CodigoEscola":13096990,
    "Nome":"ESC MUN PROFESSORA SUELI DIAS DA SILVA",
    "Localizacao":"Rural",
    "Rede":"Municipal",
    "ID_LATITUDE":-60.1777212,
    "ID_LONGITUDE":-3.200839373,
    "Eudcacao_Infantil_Total":8,
    "Eudcacao_Infantil_Creche":"--",
    "Eudcacao_Infantil_Pre-Escola":8,
    "Ensino_Fundamental_Total":22,
    "Ensino_Fundamental_Anos Iniciais":"--",
    "Ensino_Fundamental_Anos Finais":"--",
    "Ensino_Fundamental_1":"--",
    "Ensino_Fundamental_2":"--",
    "Ensino_Fundamental_3":"--",
    "Ensino_Fundamental_4":"--",
    "Ensino_Fundamental_5":"--",
    "Ensino_Fundamental_6":"--",
    "Ensino_Fundamental_7":"--",
    "Ensino_Fundamental_8":"--",
    "Ensino_Fundamental_9":"--",
    "Turmas_Unificadas_1":22,
    "Ensino_Medio_Total Medio":"--",
    "Ensino_Medio_1":"--",
    "Ensino_Medio_2":"--",
    "Ensino_Medio_3":"--",
    "Ensino_Medio_4":"--",
    "FIELD33":"--"
  },
  {
    "Ano":2012,
    "Regiao":"Norte",
    "UF":"AM",
    "CodigoMun":1301852,
    "Municipio":"IRANDUBA",
    "CodigoEscola":13097008,
    "Nome":"ESC MUN FERNANDO DAMASCENO",
    "Localizacao":"Rural",
    "Rede":"Municipal",
    "ID_LATITUDE":-60.184705,
    "ID_LONGITUDE":-3.281706,
    "Eudcacao_Infantil_Total":19.3,
    "Eudcacao_Infantil_Creche":18,
    "Eudcacao_Infantil_Pre-Escola":19.7,
    "Ensino_Fundamental_Total":18.5,
    "Ensino_Fundamental_Anos Iniciais":19.4,
    "Ensino_Fundamental_Anos Finais":17,
    "Ensino_Fundamental_1":21,
    "Ensino_Fundamental_2":15.5,
    "Ensino_Fundamental_3":26,
    "Ensino_Fundamental_4":19,
    "Ensino_Fundamental_5":20,
    "Ensino_Fundamental_6":17,
    "Ensino_Fundamental_7":20,
    "Ensino_Fundamental_8":14,
    "Ensino_Fundamental_9":"--",
    "Turmas_Unificadas_1":"--",
    "Ensino_Medio_Total Medio":"--",
    "Ensino_Medio_1":"--",
    "Ensino_Medio_2":"--",
    "Ensino_Medio_3":"--",
    "Ensino_Medio_4":"--",
    "FIELD33":"--"
  },
  {
    "Ano":2012,
    "Regiao":"Norte",
    "UF":"AM",
    "CodigoMun":1301852,
    "Municipio":"IRANDUBA",
    "CodigoEscola":13097016,
    "Nome":"ESC MUN ROSECLER GUARALDI EBLING",
    "Localizacao":"Urbana",
    "Rede":"Municipal",
    "ID_LATITUDE":-60.189727,
    "ID_LONGITUDE":-3.278758,
    "Eudcacao_Infantil_Total":20,
    "Eudcacao_Infantil_Creche":20,
    "Eudcacao_Infantil_Pre-Escola":19.9,
    "Ensino_Fundamental_Total":26.3,
    "Ensino_Fundamental_Anos Iniciais":26.5,
    "Ensino_Fundamental_Anos Finais":25,
    "Ensino_Fundamental_1":22.8,
    "Ensino_Fundamental_2":29,
    "Ensino_Fundamental_3":30.5,
    "Ensino_Fundamental_4":30,
    "Ensino_Fundamental_5":28,
    "Ensino_Fundamental_6":25,
    "Ensino_Fundamental_7":"--",
    "Ensino_Fundamental_8":"--",
    "Ensino_Fundamental_9":"--",
    "Turmas_Unificadas_1":"--",
    "Ensino_Medio_Total Medio":"--",
    "Ensino_Medio_1":"--",
    "Ensino_Medio_2":"--",
    "Ensino_Medio_3":"--",
    "Ensino_Medio_4":"--",
    "FIELD33":"--"
  },
  {
    "Ano":2012,
    "Regiao":"Norte",
    "UF":"AM",
    "CodigoMun":1301852,
    "Municipio":"IRANDUBA",
    "CodigoEscola":13097024,
    "Nome":"ESC MUN DELPHINA AZIZ",
    "Localizacao":"Rural",
    "Rede":"Municipal",
    "ID_LATITUDE":-60.1177635,
    "ID_LONGITUDE":-3.292359077,
    "Eudcacao_Infantil_Total":"--",
    "Eudcacao_Infantil_Creche":"--",
    "Eudcacao_Infantil_Pre-Escola":"--",
    "Ensino_Fundamental_Total":16.9,
    "Ensino_Fundamental_Anos Iniciais":15.3,
    "Ensino_Fundamental_Anos Finais":18,
    "Ensino_Fundamental_1":"--",
    "Ensino_Fundamental_2":12,
    "Ensino_Fundamental_3":16,
    "Ensino_Fundamental_4":18,
    "Ensino_Fundamental_5":15,
    "Ensino_Fundamental_6":22,
    "Ensino_Fundamental_7":14,
    "Ensino_Fundamental_8":"--",
    "Ensino_Fundamental_9":"--",
    "Turmas_Unificadas_1":17.7,
    "Ensino_Medio_Total Medio":"--",
    "Ensino_Medio_1":"--",
    "Ensino_Medio_2":"--",
    "Ensino_Medio_3":"--",
    "Ensino_Medio_4":"--",
    "FIELD33":"--"
  },
  {
    "Ano":2012,
    "Regiao":"Norte",
    "UF":"AM",
    "CodigoMun":1301852,
    "Municipio":"IRANDUBA",
    "CodigoEscola":13102613,
    "Nome":"ESCOLA MUNICIPAL RAIO DE ESPERANCA",
    "Localizacao":"Rural",
    "Rede":"Municipal",
    "ID_LATITUDE":-60.10313,
    "ID_LONGITUDE":-3.168301,
    "Eudcacao_Infantil_Total":7,
    "Eudcacao_Infantil_Creche":"--",
    "Eudcacao_Infantil_Pre-Escola":7,
    "Ensino_Fundamental_Total":18,
    "Ensino_Fundamental_Anos Iniciais":"--",
    "Ensino_Fundamental_Anos Finais":12,
    "Ensino_Fundamental_1":"--",
    "Ensino_Fundamental_2":"--",
    "Ensino_Fundamental_3":"--",
    "Ensino_Fundamental_4":"--",
    "Ensino_Fundamental_5":"--",
    "Ensino_Fundamental_6":12,
    "Ensino_Fundamental_7":"--",
    "Ensino_Fundamental_8":"--",
    "Ensino_Fundamental_9":"--",
    "Turmas_Unificadas_1":24,
    "Ensino_Medio_Total Medio":"--",
    "Ensino_Medio_1":"--",
    "Ensino_Medio_2":"--",
    "Ensino_Medio_3":"--",
    "Ensino_Medio_4":"--",
    "FIELD33":"--"
  },
  {
    "Ano":2012,
    "Regiao":"Norte",
    "UF":"AM",
    "CodigoMun":1301852,
    "Municipio":"IRANDUBA",
    "CodigoEscola":13102621,
    "Nome":"ESCOLA MUNICIPAL ARIAU",
    "Localizacao":"Rural",
    "Rede":"Municipal",
    "ID_LATITUDE":-60.1778007,
    "ID_LONGITUDE":-3.2738295,
    "Eudcacao_Infantil_Total":15.8,
    "Eudcacao_Infantil_Creche":"--",
    "Eudcacao_Infantil_Pre-Escola":15.8,
    "Ensino_Fundamental_Total":20.3,
    "Ensino_Fundamental_Anos Iniciais":20.4,
    "Ensino_Fundamental_Anos Finais":20.2,
    "Ensino_Fundamental_1":18.5,
    "Ensino_Fundamental_2":16,
    "Ensino_Fundamental_3":16.7,
    "Ensino_Fundamental_4":28,
    "Ensino_Fundamental_5":24.5,
    "Ensino_Fundamental_6":22,
    "Ensino_Fundamental_7":22,
    "Ensino_Fundamental_8":19,
    "Ensino_Fundamental_9":17,
    "Turmas_Unificadas_1":"--",
    "Ensino_Medio_Total Medio":"--",
    "Ensino_Medio_1":"--",
    "Ensino_Medio_2":"--",
    "Ensino_Medio_3":"--",
    "Ensino_Medio_4":"--",
    "FIELD33":"--"
  },
  {
    "Ano":2012,
    "Regiao":"Norte",
    "UF":"AM",
    "CodigoMun":1301852,
    "Municipio":"IRANDUBA",
    "CodigoEscola":13123602,
    "Nome":"ESC MUNICIPAL INDIGENA TUPANA YPORO",
    "Localizacao":"Rural",
    "Rede":"Municipal",
    "ID_LATITUDE":-60.17580342,
    "ID_LONGITUDE":-3.200828661,
    "Eudcacao_Infantil_Total":"--",
    "Eudcacao_Infantil_Creche":"--",
    "Eudcacao_Infantil_Pre-Escola":"--",
    "Ensino_Fundamental_Total":9,
    "Ensino_Fundamental_Anos Iniciais":"--",
    "Ensino_Fundamental_Anos Finais":"--",
    "Ensino_Fundamental_1":"--",
    "Ensino_Fundamental_2":"--",
    "Ensino_Fundamental_3":"--",
    "Ensino_Fundamental_4":"--",
    "Ensino_Fundamental_5":"--",
    "Ensino_Fundamental_6":"--",
    "Ensino_Fundamental_7":"--",
    "Ensino_Fundamental_8":"--",
    "Ensino_Fundamental_9":"--",
    "Turmas_Unificadas_1":9,
    "Ensino_Medio_Total Medio":"--",
    "Ensino_Medio_1":"--",
    "Ensino_Medio_2":"--",
    "Ensino_Medio_3":"--",
    "Ensino_Medio_4":"--",
    "FIELD33":"--"
  },
  {
    "Ano":2012,
    "Regiao":"Norte",
    "UF":"AM",
    "CodigoMun":1301852,
    "Municipio":"IRANDUBA",
    "CodigoEscola":13229214,
    "Nome":"CENTRO RURAL DE ENSINO COM MEDIACAO TECNOLOGICA DE IRANDUB",
    "Localizacao":"Rural",
    "Rede":"Estadual",
    "ID_LATITUDE":-60.034988,
    "ID_LONGITUDE":-3.21621,
    "Eudcacao_Infantil_Total":"--",
    "Eudcacao_Infantil_Creche":"--",
    "Eudcacao_Infantil_Pre-Escola":"--",
    "Ensino_Fundamental_Total":"--",
    "Ensino_Fundamental_Anos Iniciais":"--",
    "Ensino_Fundamental_Anos Finais":"--",
    "Ensino_Fundamental_1":"--",
    "Ensino_Fundamental_2":"--",
    "Ensino_Fundamental_3":"--",
    "Ensino_Fundamental_4":"--",
    "Ensino_Fundamental_5":"--",
    "Ensino_Fundamental_6":"--",
    "Ensino_Fundamental_7":"--",
    "Ensino_Fundamental_8":"--",
    "Ensino_Fundamental_9":"--",
    "Turmas_Unificadas_1":"--",
    "Ensino_Medio_Total Medio":17.2,
    "Ensino_Medio_1":18.3,
    "Ensino_Medio_2":16.4,
    "Ensino_Medio_3":17,
    "Ensino_Medio_4":"--",
    "FIELD33":"--"
  },
  {
    "Ano":2012,
    "Regiao":"Norte",
    "UF":"AM",
    "CodigoMun":1301852,
    "Municipio":"IRANDUBA",
    "CodigoEscola":13303210,
    "Nome":"CENTRO EDUCACIONAL ESTRELAS DO AMANHA - APAE IRANDUBA",
    "Localizacao":"Urbana",
    "Rede":"Municipal",
    "ID_LATITUDE":-60.20485711,
    "ID_LONGITUDE":-3.195109724,
    "Eudcacao_Infantil_Total":"--",
    "Eudcacao_Infantil_Creche":"--",
    "Eudcacao_Infantil_Pre-Escola":"--",
    "Ensino_Fundamental_Total":6.7,
    "Ensino_Fundamental_Anos Iniciais":6,
    "Ensino_Fundamental_Anos Finais":"--",
    "Ensino_Fundamental_1":"--",
    "Ensino_Fundamental_2":"--",
    "Ensino_Fundamental_3":"--",
    "Ensino_Fundamental_4":6,
    "Ensino_Fundamental_5":"--",
    "Ensino_Fundamental_6":"--",
    "Ensino_Fundamental_7":"--",
    "Ensino_Fundamental_8":"--",
    "Ensino_Fundamental_9":"--",
    "Turmas_Unificadas_1":7,
    "Ensino_Medio_Total Medio":"--",
    "Ensino_Medio_1":"--",
    "Ensino_Medio_2":"--",
    "Ensino_Medio_3":"--",
    "Ensino_Medio_4":"--",
    "FIELD33":"--"
  },
  {
    "Ano":2012,
    "Regiao":"Norte",
    "UF":"AM",
    "CodigoMun":1301852,
    "Municipio":"IRANDUBA",
    "CodigoEscola":13305255,
    "Nome":"CRECHE MUNICIPAL SANDRA BRAGA",
    "Localizacao":"Rural",
    "Rede":"Municipal",
    "ID_LATITUDE":-60.17835353,
    "ID_LONGITUDE":-3.197287637,
    "Eudcacao_Infantil_Total":22.7,
    "Eudcacao_Infantil_Creche":21.8,
    "Eudcacao_Infantil_Pre-Escola":22.9,
    "Ensino_Fundamental_Total":"--",
    "Ensino_Fundamental_Anos Iniciais":"--",
    "Ensino_Fundamental_Anos Finais":"--",
    "Ensino_Fundamental_1":"--",
    "Ensino_Fundamental_2":"--",
    "Ensino_Fundamental_3":"--",
    "Ensino_Fundamental_4":"--",
    "Ensino_Fundamental_5":"--",
    "Ensino_Fundamental_6":"--",
    "Ensino_Fundamental_7":"--",
    "Ensino_Fundamental_8":"--",
    "Ensino_Fundamental_9":"--",
    "Turmas_Unificadas_1":"--",
    "Ensino_Medio_Total Medio":"--",
    "Ensino_Medio_1":"--",
    "Ensino_Medio_2":"--",
    "Ensino_Medio_3":"--",
    "Ensino_Medio_4":"--",
    "FIELD33":"--"
  },
  {
    "Ano":2012,
    "Regiao":"Norte",
    "UF":"AM",
    "CodigoMun":1301852,
    "Municipio":"IRANDUBA",
    "CodigoEscola":13307339,
    "Nome":"ESC PADRE LOURENCO BENESPERI",
    "Localizacao":"Rural",
    "Rede":"Municipal",
    "ID_LATITUDE":-60.103979,
    "ID_LONGITUDE":-3.169836,
    "Eudcacao_Infantil_Total":"--",
    "Eudcacao_Infantil_Creche":"--",
    "Eudcacao_Infantil_Pre-Escola":"--",
    "Ensino_Fundamental_Total":29.5,
    "Ensino_Fundamental_Anos Iniciais":28.4,
    "Ensino_Fundamental_Anos Finais":30.1,
    "Ensino_Fundamental_1":"--",
    "Ensino_Fundamental_2":"--",
    "Ensino_Fundamental_3":38,
    "Ensino_Fundamental_4":28.7,
    "Ensino_Fundamental_5":25.8,
    "Ensino_Fundamental_6":35.8,
    "Ensino_Fundamental_7":29.3,
    "Ensino_Fundamental_8":19.5,
    "Ensino_Fundamental_9":"--",
    "Turmas_Unificadas_1":"--",
    "Ensino_Medio_Total Medio":"--",
    "Ensino_Medio_1":"--",
    "Ensino_Medio_2":"--",
    "Ensino_Medio_3":"--",
    "Ensino_Medio_4":"--",
    "FIELD33":"--"
  },
  {
    "Ano":2012,
    "Regiao":"Norte",
    "UF":"AM",
    "CodigoMun":1301852,
    "Municipio":"IRANDUBA",
    "CodigoEscola":13307355,
    "Nome":"ESC PEQUENOS ACAMPANTES",
    "Localizacao":"Rural",
    "Rede":"Municipal",
    "ID_LATITUDE":-60.185535,
    "ID_LONGITUDE":-3.2828727,
    "Eudcacao_Infantil_Total":22.4,
    "Eudcacao_Infantil_Creche":"--",
    "Eudcacao_Infantil_Pre-Escola":22.4,
    "Ensino_Fundamental_Total":"--",
    "Ensino_Fundamental_Anos Iniciais":"--",
    "Ensino_Fundamental_Anos Finais":"--",
    "Ensino_Fundamental_1":"--",
    "Ensino_Fundamental_2":"--",
    "Ensino_Fundamental_3":"--",
    "Ensino_Fundamental_4":"--",
    "Ensino_Fundamental_5":"--",
    "Ensino_Fundamental_6":"--",
    "Ensino_Fundamental_7":"--",
    "Ensino_Fundamental_8":"--",
    "Ensino_Fundamental_9":"--",
    "Turmas_Unificadas_1":28,
    "Ensino_Medio_Total Medio":"--",
    "Ensino_Medio_1":"--",
    "Ensino_Medio_2":"--",
    "Ensino_Medio_3":"--",
    "Ensino_Medio_4":"--",
    "FIELD33":"--"
  }
];
  return a;
}
